spring:
#  zipkin:
#    base-url: http://localhost:9411
  application:
    name: web-admin-feign
  boot:
    admin:
      client:
        url: http://localhost:8084
server:
  port: 8004
  servlet:
    context-path: /
eureka:
  instance:
    prefer-ip-address: true
    instance-id: web-admin-feign
  client:
    service-url:
      defaultZone: http://localhost:7003/eureka/
feign:
  hystrix:
    enabled: true
